{{- $flags := .Flags }}
{{- $base_port := .Flags.port | atoi -}}

version: "3"
services:
  cli.{{$flags.domain}}:
    image: synadia/nats-server:nightly
    dns_search: {{$flags.domain}}
    entrypoint: /bin/sh
    networks:
      - shared
    {{- if $flags.mount }}
    volumes:
      - {{ $flags.mount }}
    {{- end }}

{{- range $cluster := $flags.clusters | atoi | seq | split " " }}
  {{- range $node := $flags.members | atoi | seq | split " " }}
    {{- $client_listen := (sub (add $base_port (mul (sub $cluster 1) 100) $node) 1) -}}
    {{- $node_name := cat "n" $node ".c" $cluster | nospace }}
  {{ $node_name }}.{{ $flags.domain}}:
    dns_search: c{{ $cluster}}.{{$flags.domain}}
    image: {{ $flags.image }}
    environment:
      GATEWAY: c{{$cluster}}
      NAME: {{ $node_name }}
      ADVERTISE: {{ $node_name }}.{{$flags.domain}}:{{ $client_listen }}
    networks:
      - shared
      - nats-cluster{{ $cluster }}
    ports:
      - {{ $client_listen }}:4222
    volumes:
      - ./cluster.conf:{{ index $flags "config-path" }}
      - {{ $flags.data }}/{{ $node_name }}:/data
      {{- if $flags.mount }}
      - {{ $flags.mount }}
      {{- end }}
  {{end }}
{{- end }}

networks:
{{- range $cluster := $flags.clusters | atoi | seq | split " " }}
  nats-cluster{{ $cluster }}: {}
{{- end }}
  shared: {}
